steps:
- name: "gcr.io/cloud-builders/docker"
  args:
  - build
  - "--tag=gcr.io/fake-news-bsky-detection/fake-news-flask-server-image"
  - "--file=./Dockerfile"
  - "."
  secretEnv: ['HOPSWORKS_API_KEY']

options:
  machineType: 'N1_HIGHCPU_8' # 8 vCPUs, 7.2 GB memory

availableSecrets:
  secretManager:
  - versionName: projects/fake-news-bsky-detection/secrets/HOPSWORKS_API_KEY/versions/latest
    env: 'HOPSWORKS_API_KEY'
  
images:
- "gcr.io/fake-news-bsky-detection/fake-news-flask-server-image"


