  name: fake_news_on_demand

  on:
    workflow_dispatch:
    schedule:
      - cron: '6 14 * * *'

  jobs:
    schedule_pipelines:
      runs-on: ubuntu-latest

      permissions:
        contents: write

      steps:
        # Step 1: Checkout repository
        - name: Checkout repository
          uses: actions/checkout@v4

        # Step 2: Set up Python environment
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
            cache: 'pip'

        # Step 3: Install dependencies
        - name: Install Python packages
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        # Step 4: Execute pipelines
        - name: Execute Python workflows
          env:
            HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          run: |
            python on_demand_features_pipeline.py

        # Step 5: Commit and push generated files
        - name: Publish updated data to repository
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: "Fake News Bsky published"
            commit_options: '--no-verify --signoff'
            file_pattern: 'figures/*' 
            repository: .
            status_options: '--untracked-files=no'
